apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-db
spec:
  provider:
    vault:
      server: "https://vault.lefrancis.org" 
      path: silas/k8_db
      version: "v1"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: {{ .Values.postgres.namespace }}
          key: token