apiVersion: v1
kind: Secret
metadata: 
  name: postgres-db-secrets
  namespace: {{ .Values.postgres.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.postgres.database }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"