apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  name: postgres-db-external-secrets
  namespace: {{ .Values.postgres.namespace }}
spec: 
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: postgres-db-secrets
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.vault_key_path }}
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.vault_key_path }}
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.vault_key_path }}
        property: POSTGRES_PASSWORD
