apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  name: postgres-db-external-secrets
  namespace: {{ .Values.postgres.namespace }}
spec: 
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: postgres-db-secrets
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: "{{ .POSTGRES_DB }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.env }}
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.env }}
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.env }}
        property: POSTGRES_PASSWORD
