services:
  postgres:
    image: postgres:15-alpine
    container_name: postgress_db_real_world_cont
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER} -d ${DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      target: production
      context: ./Backend/fastapi
      dockerfile: Dockerfile.api
    container_name: fastapi_real_world_cont
    env_file:
      - .env
    environment:
      APP_ENV: dev
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn conduit.app:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - ./Backend/fastapi:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      target: production
      context: ./Frontend/react-recoil
      dockerfile: Dockerfile.fe
    container_name: client_real_world_cont
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: true
      BROWSER: none
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/react-recoil:/app
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data: