apiVersion: v1
kind: Service
metadata:
  name: react-recoil-service
  namespace: {{ .Values.apps.namespace }}
  labels:
    {{- include "react-recoil.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "react-recoil.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000