apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect
  namespace: {{ .Values.apps.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      sectionName: http  
  hostnames:
    - {{ .Values.http_route.hostnames.api }}
    - {{ .Values.http_route.hostnames.app }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301