apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-httproute
  namespace: {{ .Values.apps.namespace }}
spec:
  hostnames:
    -  {{ .Values.http_route.hostnames.app }}
  parentRefs:
    - name: {{ .Values.gateway.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.apps.react_recoil.service }}
          port: 80
