apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-httproute
  namespace: apps-namespace
spec:
  hostnames:
    # - "{{ include "react-host.name" . }}"
    -  "api.lefrancis.com"
  parentRefs:
    - name: app-gateway
  rules:
    # API backend
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: fastapi-service
          port: 80
