apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-httproute
  namespace: apps-namespace
spec:
  hostnames:
    # - "{{ include "react-host.name" . }}"
    -  "app.lefrancis.com"
  parentRefs:
    - name: app-gateway
  rules:
    # React frontend
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: react-recoil-service
          port: 80
