apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: apps-namespace
type: Opaque
data:
  token: aHZzLkNBRVNJRUZVLVdVS1R2dnAza2c2bUNDakNnaERHT255YUl4VnQ5OFNRbjhHQ2JuS0doNEtI
R2gyY3k1U1pqRklRVTVHUzJaeWNYUmhhbmR5WnpWbk5raFFhbVk=