apps:
  namespace: apps-namespace
  fastapi:
    service: fastapi-service
  react_recoil:
    service: react-recoil-service

gateway_class:
  name: kong-gatewayclass

gateway:
  name: kong-gateway-api

http_route:
  hostnames:
    api: "api.lefrancis.org"
    app: "app.lefrancis.org"
