postgres:
  namespace: postgres-namespace
  replicas: 1
  database: francis_db
  image: postgres:16
  migration_image: silasfrancis/db-migration-dev:e1ea814-0000-ge1ea814
  password: francisdb
  port: 5432
  user: francis_user
