postgres:
  namespace: postgres-namespace
  replicas: 1
  database: francis_db
  image: postgres:16
  migration_image: silasfrancis/db-migration-dev:ddce371-0000-gddce371
  password: francisdb
  port: 5432
  user: francis_user
