vault_key_path: linode/lke
postgres:
  namespace: postgres-namespace
  service: postgres-service
  replicas: 1
  image: postgres:16
  migration_image: silasfrancis/db-migration-dev:e46aca1
  port: 5432