apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-httproute
  namespace: {{ .Values.apps.namespace }}
spec:
  hostnames:
    - {{ .Values.http_route.hostnames.api }}
  parentRefs:
    - group: gateway.k8s.aws
      name: {{ .Values.gateway.name }}
      kind: Gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.apps.fastapi.service }}
          port: 80
