vault_key_path: aws/eks 
postgres:
  namespace: postgres-namespace
  replicas: 2
  image: postgres:16
  migration_image: silasfrancis/db-migration-main
  migration_image_tag: e61dec3-0000-ge61dec3
  port: 5432
