backend/fastapi:
    - backend/fastapi/**
    - .github/workflows/test.yaml
    - .github/workflows/build-push.yaml
frontend/react-recoil:
    - frontend/react-recoil/**
    - .github/workflows/test.yaml
    - .github/workflows/build-push.yaml 
backend/postgres_db:
    - backend/postgres_db/**