version: "3"

tasks:
  generate-image-repo:
    vars:
      SERVICE: "{{.CLI_ARGS}}"
    cmds:
      - |
        echo "Service argument passed: {{.SERVICE}}"  # For debugging

        case "{{.SERVICE}}" in
          "Backend/fastapi")
            echo "silasfrancis/devops-api-"
            ;;
          "Frontend/react-recoil")
            echo "silasfrancis/devops-client-"
            ;;
          *)
            echo "Unknown service: {{.SERVICE}}"
            exit 1
            ;;
        esac
