version: "3"

tasks:
  generate-image-repo:
    vars:
      SERVICE: "{{.ARGS}}"
    cmds:
      - |
        case "{{.SERVICE}}" in
          "Backend/fastapi")
            echo "silasfrancis/devops-api-"
            ;;
          "Frontend/react-recoil")
            echo "silasfrancis/devops-client-"
            ;;
        esac
