version: "3"

tasks:
  generate-image-repo:
    cmds:
      - |
        SERVICE="{{index .ARGS 0}}"
        case "$SERVICE" in
          "Backend/fastapi")
            echo "silasfrancis/devops-api-"
            ;;
          "Frontend/react-recoil")
            echo "silasfrancis/devops-client-"
            ;;
        esac
