apiVersion: v1
kind: Namespace
metadata:
  name: apps-namespace

---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-namespace

---

apiVersion: v1
kind: Namespace
metadata:
  name: vault-auth

---

apiVersion: v1
kind: Namespace
metadata:
  name: kube-system



  