apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-app-tls
  namespace: apps-namespace
spec:
  secretName: tls-secret
  dnsNames:
    - api.lefrancis.org
    - app.lefrancis.org
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
