
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVWlaaGc2SmVWNUV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1qZ3hOVEV4TkRaYUZ3MHpOakF5TWpZeE5URTJORFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN4NkVDK254TGE1a0ExZzkzRmxIU2IzUzhLVEN3UXZKS2w4d25XTDNzN2xRQVdzcmFwQzA1azR0SjMKamJQRC81TVl6YjR1RFBQc21xWW9UMlRROXRNaW9pQjFtcC9nSk5jQWx0WGg4eXBkVG95S3RKbGRKR2oyRHkwdApNejZXdUo2cVVEZXE5bzEwNUtRWGxRbVltMnc4R3EzNzJOVnlMSkZTMVoxZm1udVBLVjdnTmplME9mUUJCeC8rCmxQZ3Bxa1pDd0hQWkI4M3prcWI3WE44NnlxeXdhRXRnQ3BWS1hNUjIrS2ZGRUQ3R24yNkhNM3BvRm12MEhtOTUKb2gzcFhhWUE3MXNjL1lIUVNkVzJnRm84dk44ZHB6cTdCYkVHR0tDNCtaUWQzU2xzQll3U1ZOOEM4ZmJ4YXpONQpZK2dFZitsSm9sQ21qNkZzZER2WUZ6UFlUano1QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUTExOb1p3VmZRMFBITldEcmJTMDV2dVlTNU16QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2RRbU9LWDFYUAp2MDFZRUM4RkxOUms5K1VRaFR4endaZExTc09hdGZsd2pLOVBEMUFOV2JJdlBWL1RRTmp2S3hDcnZHNkt1UCtuCkxhZXlnNGVXRXJ0SjB6YjBvRTJkMmQyaHJyS1dpMGRQTFVjYWZMZXFiVW0wbmxOYnFzQzg5N2wwN2EwK2w0YzEKQVpxaWlreTZ1d09Ed2VTb2ZKcTFPNnp3YTBLdU1odHE0NFZDZXBuR2JERERxajZyalhiMDhKdFlKbXJsTGpJNwpIWlpYQmp3Vk5qU0RlRTQ0dXE5bWp5ZDZoSW5hTk1yWTZ6aUVtcU1kbCtyUXR1VEFlSnp0K3NuV01SVXBsbFV0Cmdtc2hwQnlmb1BvYk5SQTZNcGZqY2d4bWpoQlZrYTFTa2J4Y1RtSzdHSGV0cmRaMlB6LzFxL2hFQnhmbU9kbisKYzBzT0o3d3Q1NTg0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8438c60b-7d4c-4bed-ac94-f9ca7b2fde87.us-lax-2-gw.linodelke.net:443
  name: lke574346

users:
- name: lke574346-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhTZzBpM2l4aWFkVDIxU25HTkJXRHhUZFZGQ0hiX3BkRWdlclpCYi1uUUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbDZ3cmMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzMyNDE1MWEtZGU2MS00NzUxLTlkZjYtY2FiM2JlOTE5OTcxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.qzes3JVK4AIvmj7JKXY5Q2tDxY1obpdAv6YqJN-ddR-A-1V2lcQBRhXvn419qHkQi0GDsKv8mATJk-QBZqxicwxaQjNEjJXBYnKPyvDjKWUfj_YIp67Uqe3Yea4dxarSnjamw5HHkyyG4lqIQifKrbnU6fT9j57vsgqJreIB_WKDUF_fut5wSNg1G8MIUHgiKFJLXulc4ZYEqnDqzwo1G6rUkiTfGsv0d6tbheSw6SgfYIaiA2gp7nOT28XQ3L1RJa34k7DXkguHz5sbgBLzPYu6RrmlC3iISfiGn4Ai0rVmsJa97I2T1oT2j4Sd6ioyR7qyjY4Zf4Bx5PN7W06CNA

contexts:
- context:
    cluster: lke574346
    namespace: default
    user: lke574346-admin
  name: lke574346-ctx

current-context: lke574346-ctx
