
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVHNUYmlGOGxjNU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1qSXlNVEkwTWpaYUZ3MHpOakF4TWpBeU1USTVNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURuNGR2dHlpK1RUWlFycms3QVFVTWc0RnR4K291ZUp3WGJWcjJtZXRTYUx3ZU9hbHR1Uit4R2wrd0oKelBEclN2ZU1ZSENNazRlYm45MkpIMjNNR3M5dlhqRHNUZ0ZwRUEwQzgrOEhDRzYwVU1tTVRNNkl2YU9vMS9NUQo1SzhuZVhZeHljS2NPL1dqeEN2d09hd3F2R0dGSXhIbmxIV3BIM2lHR2pIdXh0cGVZcjluU3BzM3ZIdU03aU5rCisycGRVRzJYdWlsQzY0emVjMEk3cmhOR1ZUKzhiRThKZ05wa0VweXoySDZ1MWlSWFJ4dHh1bkdSWEo0Rld1VmwKQzRjWmR5UWZEZGUyaG9mZlVYeW1lZ3A3cW0wT3VCaVN6UmVBZERIb3J5UWFaeWlmc0gzeUY3T3hKaHYyUUhHNwpDcG1oKzZZb3ZnS3o1K0NTN2UxTFE5Vis2RFlOQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSbWdiUjBGaHZBQmh5ZHJJL1lUR0R6d1JOaGVqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQk5rd1BJWGFTOQpoRDFmNU9raWtpN0dkRnU0alZsM2VaQzZuWnBTK3lTcjI0K1pSWVgzdkJOOWFQZFZLVUE4aTE5VXlPWUJhOGp4CnBDY0xndG52R3ZLZ2lYUGdDUmNienlJcDJjbDduaG1qeVY5c1ZySkZTdnllSmNkeEpobFI2c1ltZTJXQ2tEY0sKRGRsRDd4R09uWFJoSDVzSU1IbmI3RnIrb2d4S1c1RU90Y3h3NHpGM1BqcitrQ05tZGVES0Fsb1QxYTFvZjh4cgpld3ptUkRxcEV3dGpWM3FKMHYzWWVmSkJmNVV6MU1wcG9GSWlQMVFJeEdJUUtvZ0xSSTkyWC9iTTROcndXcDBLClZDUVVXM2NnbWlrQnlpbkpJeGNUVHpMV3ZxK1NiWDFUaWJyWis4UnhuZitVdWUzZC9kT1VIaEs3SERsV3hVamQKMER3MWlHdkVadWx2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://7ec5c5d6-88eb-4084-a495-c8acac4dfd1b.us-lax-2-gw.linodelke.net:443
  name: lke559731

users:
- name: lke559731-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImIxTi1EY190cHFmREJxWVNtdXQzX2hLUV9ic3pObEJXT2l5eUYyeTc3MXcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tNG40YjYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDY0NDE1YzctY2U0ZS00YzMxLWE4ZjctMTNmYTI3NWYxYWQ2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.SUEUj_C6G03duGQ9icHhnQ3cdj3ol95mSmOrkgZAAnoJl0XdFAl2j1Y1bSqSQBjTsKbQ2NkhKBA0WQn4czqq31UOY_2RJmftbqO8FL_7jiAHSHt71siTAbveUx-rXGFeB-22utK8U4IWXtkiUVniI-fTiOB8VV6yMM12AlW9gipzhU-vDQDnS2vSRetBAmKF4rnWa6bRtoZAuwD8t-cFBvF76z4CQsp0CtXh9wc_kUp_8bYr5ScCJ_xs-0H0mDgdM8bdKfgbmeBmZ-KBCdvw8gQmxmClLU4909rmomVkgrZNugOjMlLbMFjaPDYh4fWAl-SHdkO191A_ug4ZyAx1hg

contexts:
- context:
    cluster: lke559731
    namespace: default
    user: lke559731-admin
  name: lke559731-ctx

current-context: lke559731-ctx
