apiVersion: v1
kind: Secret
metadata:
  name: vault-k8s-auth-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: eso-service-account
type: kubernetes.io/service-account-token