apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "https://vault.lefrancis.org"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.vault_mountPath }}
          role: {{ .Values.vault_role }}
          serviceAccountRef:
            name: eso-service-account
            namespace: {{ .Values.namespace }}