env: dev

apps:
  namespace: apps-namespace
  fastapi:
    replicas: 1
    image: silasfrancis/devops-api-dev:ddce371-0000-gddce371
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  reactRecoil:
    replicas: 1
    image: silasfrancis/devops-client-dev:ddce371-0000-gddce371
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 1Gi
postgres:
  namespace: postgres-namespace
  database: francis_db
  password: francisdb
  port: 5432
  user: francis_user
