apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fastapi-external-secrets
  namespace: {{ .Values.apps.namespace }}
spec: 
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: fastapi-secrets
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: {{ .Values.env }}
      property: SECRET_KEY
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: {{ .Values.env }}
      property: JWT_SECRET_KEY
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: {{ .Values.env }}
      property: POSTGRES_HOST
  - secretKey: POSTGRES_PORT
    remoteRef:
      key: {{ .Values.env }}
      property: POSTGRES_PORT
  - secretKey: POSTGRES_DB
    remoteRef:
      key: {{ .Values.env }}
      property: POSTGRES_DB
  - secretKey: POSTGRES_USER
    remoteRef:
      key: {{ .Values.env }}
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: {{ .Values.env }}
      property: POSTGRES_PASSWORD
