apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: {{ .Values.apps.namespace }}
  labels:
    {{ include "fast-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{ include "fast-api.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080