
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVWRsL1ZGYUNoSzh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1qSXhORE0xTWpWYUZ3MHpOakF4TWpBeE5EUXdNalZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM3NUlmanNEajZnNjdkb3lKVWpwQTMzZnNuc2lmaDZ4WEZWZitrWkVQZXFZUTVqaU0zOUFOYTdpMmIKRWZZaTdMeHdzUGVNREhoa2tXOWZMQXVvSkFrWDdrWUpFSVRSalp2Z2x1WmFvQkdFeVNnbGVlV2NtMXhaQ1FhWQpCRDNyTG1iVGNocEhzM29CNkxoTTVBcFFvVFMwTi9wS2laNGRERGJWL0pIYndHOUcrcEtVRFU5TUVKOEcvOEYxCmh3VEZyNjBBcktWcW81d1pFNW9CS0tJVEJBOXAreGJOTUppMlV4WDRqRFI1N2NQaEs1MnlGb3cxb3dqaWlSa0UKdXdOWU9YMnhYeGZlUElSOEhtOUdPUVhDZksxZ2pBamRKNTlYaGJIQU1Qd0NLa1hjaklQaWRHOFU4cmZMZEpNegpLSHA0Zm1vb2RCVnFGWGhUblpGK0tyeVJvblNIQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSNkNDc1BtTkpGbzEzMkpzRGpnRUxSM0NrcEFqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2NLUWk0TnhITwptZVdxTDJhMnRUTEJvRnhHU1d0eHlDS2xpTzVGQURvRkVJN0hTMG0yam5uazZrWitrYjRRUUo0MUo5aDQvNDJkCmRZcU1sZmhqZnNpZjZYSXFGVHhGMGdRR3E5WTQvd3pyZ05PUElsUUQ4Y3Nkcm8vODVHa3VLMVQzOU90dXlUQ1kKUThqcE55T3VXKzBvbVN2MXk0U2tqeVpSbE1mZHpZd2NQL0VMRUZ1NExUL0oxUHBOcnN3WlFKRGw0dmEwQzVkMAo3dVZReVVJQjE0a3FYbGlER1UrUEJJTEtKMzF5ZmcvSnZpTDZVUHFuRE4ybytRSGdlbDdPYVZxYWdNc2tpanJHCi9BR3J4VjF6aklLcnA1QUVvN0dRam5qTkRWV1NCMmI0Ti9LaUd5dXVxYlZxcWF6YnhvN3pUcHYxN0p3ekZaeXkKcVY1VThDQk5VUlIrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://30375bfb-aa73-4ca3-ba61-3a410e5505c1.us-lax-2-gw.linodelke.net:443
  name: lke559482

users:
- name: lke559482-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlM4UG5xeXhjUkFyOTBHVVFHdk1xaWhLakV0NW8wSFpPbjlQQk1EMndwaGMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tY3hyNXYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTc1NWJlZDctZTc2Yi00YzhhLTkwMTUtYTYyMzAzMmFhN2NmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.lwaFim3flmOdZr_SD1sCKzLuGekwNUOL8zIoXYtFz9o_6YAou_Ywg93IEx90YkLWNfjVRjTD3r9YTTezcf2iEXzEmjbOW7NQeywEvWMSVoqgvZ12rSO6bh5CvDuOASR5bMTCd5xiZx7qpkPtbPpc_b0CZ0zPouil1CVEaKEgP-BkDB9wjQVZNvcvBsSJgA6zoSzAHO8rg-gILkPDqmCEoBs1q__MS7eQmSrsag_7Nn45_0zvzWEHRvOXWlmHuOxleAgrs8Ydh3MDmzEj4bCvRRjGNCRAD4BZNOVQaS4rOebsyaRFueuSJ3j2caymJ3njuWDA76NSTXmfBRHeut-2tQ

contexts:
- context:
    cluster: lke559482
    namespace: default
    user: lke559482-admin
  name: lke559482-ctx

current-context: lke559482-ctx
